import re

from daily_briefing.render import (
    PALETTE,
    markdown_to_html,
    parse_briefing,
    render_html,
    strip_preamble,
)

DOC = """Here is your briefing:

# Daily briefing — Tuesday 6 October
**Action today:** Buy **Museumnacht** tickets.

## LLM engineering
**Try:** something.

## Open-source radar
- **Claude** — A meetup.
- plain item

## Book ahead
**ACTION**

- [Museumnacht — 7 November](https://example.com): buy now.

**On the radar**

| What | When |
|---|---|
| Thing | Fri |
## Extra
Text

Sources: example.com failed.
"""

ICONS = {"LLM engineering": "🧠", "Open-source radar": "🛠️"}


def test_preamble_dropped():
    assert strip_preamble(DOC).startswith("# Daily briefing")


def test_header_fields():
    b = parse_briefing(DOC, ICONS)
    assert b.subject == "Daily briefing — Tuesday 6 October"
    assert (b.kicker, b.headline) == ("Daily briefing", "Tuesday 6 October")
    assert b.read_min >= 1
    assert "Museumnacht" in b.action_html and not b.action_html.startswith("<p")
    assert b.preheader == "Buy Museumnacht tickets."


def test_sections_and_icons():
    b = parse_briefing(DOC, ICONS)
    assert [s.title for s in b.sections] == [
        "LLM engineering",
        "Open-source radar",
        "Book ahead",
        "Extra",
    ]
    assert [s.icon for s in b.sections] == ["🧠", "🛠️", "•", "•"]


def test_icon_lookup_ignores_case_and_numbering():
    b = parse_briefing("# T\n\n## 2. open-source RADAR\nx\n", ICONS)
    assert b.sections[0].icon == "🛠️"


def test_heading_after_table_still_splits():
    b = parse_briefing(DOC, ICONS)
    book = b.sections[2].html
    assert "<table" in book and "Extra" not in book


def test_sources_line_moves_to_note():
    b = parse_briefing(DOC, ICONS)
    assert b.note == "Sources: example.com failed."
    assert "Sources:" not in b.sections[-1].html


def test_no_sections_goes_to_intro():
    b = parse_briefing("Some text without structure.\n\n- a list\n")
    assert b.sections == []
    assert "Some text" in b.intro_html and "<li" in b.intro_html
    assert b.subject == "Daily briefing"


def test_authored_emphasis_and_list_punctuation_survive():
    html = markdown_to_html(
        "**ACTION**\n\n**On the radar**\n\n- **Claude** — A meetup.\n- plain item"
    )
    assert re.findall(r"<strong[^>]*>(.*?)</strong>", html) == ["ACTION", "On the radar", "Claude"]
    assert "</strong> — A meetup." in html
    assert html.count("<li") == 2
    assert "<span" not in html and "<div" not in html


def test_lead_in_and_linked_emphasis_inherit_surrounding_colour():
    html = markdown_to_html("**Try:** this and [**read more**](https://example.com)")
    assert html.count('style="color:inherit;"') == 2
    assert 'href="https://example.com"' in html
    assert "text-decoration:underline;" in html
    assert "border-bottom" not in html


def test_link_inside_emphasis_stays_burgundy_and_underlined():
    html = markdown_to_html("**[tracewise](https://example.com)**")
    assert 'href="https://example.com" style="color:#713B46;' in html
    assert "text-decoration:underline;" in html


def test_masthead_and_section_headings_are_semantic_without_icons():
    html = render_html(parse_briefing(DOC, ICONS))
    assert re.findall(r"<h1[^>]*>(.*?)</h1>", html) == ["Daily briefing"]
    assert re.findall(r"<h2[^>]*>(.*?)</h2>", html) == [
        "LLM engineering",
        "Open-source radar",
        "Book ahead",
        "Extra",
    ]
    masthead = re.search(r'<td style="([^"]*)">\s*<h1', html).group(1)
    assert "background:#713B46;" in masthead and "padding:24px;" in masthead
    h1_style = re.search(r'<h1 style="([^"]*)">', html).group(1)
    assert "font-size:48px;" in h1_style and "color:#F7F4ED;" in h1_style
    assert "line-height:1.05;" in h1_style and "letter-spacing:-1px;" in h1_style
    h2_style = re.search(r'<h2 style="([^"]*)">', html).group(1)
    assert "font-size:26px;" in h2_style and "color:#713B46;" in h2_style
    assert "border-top:1px solid #713B46;" in html
    assert "Tuesday 6 October" in html and "min read" in html
    assert "🧠" not in html and "🛠️" not in html and "⚡" not in html
    assert "border-radius" not in html and "text-transform" not in html


def test_optional_opening_and_footer_content():
    bare = render_html(parse_briefing("# Title\n\n## Only\nx"))
    assert "Action today" not in bare and "Edit your sections" not in bare
    assert "Sources:" not in bare
    full = render_html(parse_briefing(DOC), repo_url="https://example.com/edit", generated="now")
    assert "Action today" in full and "Buy" in full
    assert "border-left:1px solid #713B46;" in full
    label = re.search(r'<p style="([^"]*)">Action today</p>', full).group(1)
    assert "font-size:18px;" in label and "font-style:italic;" in label
    assert "Sources: example.com failed." in full
    assert "Generated by Codex · now" in full
    assert 'href="https://example.com/edit"' in full


def test_long_content_tables_and_code_have_fluid_wrapping():
    word = "Long" * 80
    html = render_html(
        parse_briefing(
            f"# {word}\n\n## {word}\n[{word}](https://example.com)\n\n"
            f"| Detail |\n|---|\n| {word} |\n\n```text\n{word}\n```\n\n> Quote"
        )
    )
    assert html.count(word) == 6
    assert "max-width:640px;" in html
    assert "table-layout:fixed;" in html
    assert "overflow-wrap:anywhere;" in html
    assert "word-break:break-word;" in html
    assert "white-space:pre-wrap;" in html
    assert "<blockquote" in html and "<pre" in html and "<th" in html


def test_list_directly_after_paragraph():
    assert "<li" in markdown_to_html("Intro line\n- item\n")


def test_every_paragraph_inline_styled():
    html = markdown_to_html("one\n\ntwo\n")
    assert html.count('<p style="') == 2


def test_render_html():
    html = render_html(
        parse_briefing(DOC, ICONS),
        repo_url="https://github.com/a/b",
        generated="now",
    )
    for text in ("Tuesday 6 October", "LLM engineering", "Book ahead", "4 sections", "now"):
        assert text in html
    assert "https://github.com/a/b" in html
    assert PALETTE["text"] in html
    assert "{{" not in html


def test_singular_section_count():
    html = render_html(parse_briefing("# T\n\n## Only\nx\n"))
    assert "1 section · 1 min read" in html


def test_raw_html_is_escaped():
    from daily_briefing.render import markdown_to_html

    html = markdown_to_html("hi <img src=x onerror=alert(1)> <script>alert(1)</script>")
    assert "<img" not in html and "<script" not in html
    assert "&lt;script&gt;" in html


def test_markdown_images_are_not_rendered():
    from daily_briefing.render import markdown_to_html

    assert "<img" not in markdown_to_html("![a](https://track.example/p.png)")
